// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_WDa2lTKa02oy5vhW8ElheCDSXugCnxk',
    appId: '1:480965195745:web:1a9c96c4b1932426b5c4a0',
    messagingSenderId: '480965195745',
    projectId: 'recbekia-85d2b',
    authDomain: 'recbekia-85d2b.firebaseapp.com',
    storageBucket: 'recbekia-85d2b.appspot.com',
    measurementId: 'G-GHP6FYTCYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgzNXxRV-B5VjKUULB01REIcfYNIajl0',
    appId: '1:480965195745:android:f5d451f8e5bc7fd4b5c4a0',
    messagingSenderId: '480965195745',
    projectId: 'recbekia-85d2b',
    storageBucket: 'recbekia-85d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNyINsiuRxpBnAhuW3xvR3ejKTfaorZ04',
    appId: '1:480965195745:ios:ec84b62d8790f013b5c4a0',
    messagingSenderId: '480965195745',
    projectId: 'recbekia-85d2b',
    storageBucket: 'recbekia-85d2b.appspot.com',
    iosBundleId: 'com.example.recbekia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNyINsiuRxpBnAhuW3xvR3ejKTfaorZ04',
    appId: '1:480965195745:ios:ec84b62d8790f013b5c4a0',
    messagingSenderId: '480965195745',
    projectId: 'recbekia-85d2b',
    storageBucket: 'recbekia-85d2b.appspot.com',
    iosBundleId: 'com.example.recbekia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_WDa2lTKa02oy5vhW8ElheCDSXugCnxk',
    appId: '1:480965195745:web:a4b6a1743b5932eab5c4a0',
    messagingSenderId: '480965195745',
    projectId: 'recbekia-85d2b',
    authDomain: 'recbekia-85d2b.firebaseapp.com',
    storageBucket: 'recbekia-85d2b.appspot.com',
    measurementId: 'G-M6WW79VDJR',
  );

}